# -*- coding: utf-8 -*-
"""run_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FrffAfv0UfHE-SEAAxVaTuk7yQ9kIkRZ
"""

from traffic_cleaning_pipeline import TrafficCleaningPipeline

if __name__ == "__main__":

    pipeline = TrafficCleaningPipeline(
        input_path="../data/traffic_raw.csv",
        output_path="../outputs/traffic_cleaned.parquet"
    )

    pipeline.run()